### ISSUE TITLE
Android build error > A problem occurred starting process 'command ti'

### ISSUE THREAD

**Issue by justintoth** [NetrisTV/ti.appcenter#3]
I wasn't able to get the Android module to build, despite following the directions in the README:

```
JustinsMBP2018:android justintoth$ ./gradlew tiBuild
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred starting process 'command 'ti''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
```

Here are the verbose logs: https://gist.github.com/justintoth/2790fc86a2949013727151bde2dd458c

**Comment by justintoth** [comment]
The alternative build method with the appc command failed as well: https://gist.github.com/justintoth/d07726b8114027e366fe224f6a6bfeca

**Comment by drauggres** [comment]
> A problem occurred starting process 'command 'ti''

[Titanium CLI](https://github.com/appcelerator/titanium)
`[sudo] npm install -g titanium`
> The alternative build method with the appc command failed as well: 

>you ~should~ MUST download App Center SDK and put into android/app/libs (or android/lib which is symlink). After that you should run

Run `./gradlew downloadLibrary` from `android` directory to download App Center SDK.

**Comment by drauggres** [comment]
Now android module uses standard (for Ti SDK 9) structure.
You can use `appc run -p android --build-only` to build it (without any additional actions).

**Comment by justintoth** [comment]
I have it building and running now, thanks for the quick response!! One unrelated question... Is there a method for manually sending an exception? It seems to only send unhandled exceptions currently. It'd be useful in a try/catch or even a global error handler like this:

```
Ti.App.addEventListener('uncaughtException', function tiAppErrorListener(evt) {
			// TODO: Send exception to App Center.
		});
```

**Comment by drauggres** [comment]
AFAIK, they don't provide such methods in the SDK (let me know, if I missed it).
You can try to [Upload crashes via API](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes) (I have not tried).

**Comment by justintoth** [comment]
The Crashes.trackError method is what can accomplish this: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#handled-errors

**Comment by justintoth** [comment]
I think something like this might work:

```
@Kroll.method
	public void trackError(String exception, KrollDict[] properties)
	{
		Map<String, String> propertiesHash = new HashMap<String, String>();
		for (KrollDict property : properties) {
			String key = null;
			String value = null;
			if (property.containsKeyAndNotNull("key")) {
				key = property.getString("key");
			}
			if (property.containsKeyAndNotNull("value")) {
				value = property.getString("value");
			}
			propertiesHash.put(key, value);
		}

		Crashes.trackError(new Exception(exception), propertiesHash, null);
	}
```

Unfortunately after pulling latest (2.0.0), building and generating the zip, and then importing it into my project, my app fails to build:

[ERROR] Could not find all required Titanium Modules:
[ERROR]    id: ru.netris.mobile.appcenter	 version: latest	 platform: android,commonjs	 deploy-type: development

Not sure what I'm missing, it was working before with what "./gradlew tiBuild" generated but doesn't work with "appc run -p android --build-only".

**Comment by drauggres** [comment]
v2.0.0 requires Ti SDK 9+ (it has proper gradle support)

UPD: there is no code changes in v2.0.0, only files rearrangement.
